# Generated by Django 5.1.5 on 2025-03-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='timestamp',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='transactions',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactions',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
