# Generated by Django 5.1.5 on 2025-03-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionamount',
            name='monthly_subscription_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionamount',
            name='yearly_subscription_amount',
            field=models.IntegerField(default=0),
        ),
    ]
