# Generated by Django 5.1.5 on 2025-03-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='in_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='in_trash',
            field=models.BooleanField(default=False),
        ),
    ]
