# Generated by Django 5.1.5 on 2025-04-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
