# Generated by Django 5.0.2 on 2024-12-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='site_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='site_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='site_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='site_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
