# Generated by Django 5.1.5 on 2025-04-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_alter_transactions_checkout_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
