# Generated by Django 5.1.5 on 2025-03-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_rename_timestamp_transactions_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='checkout_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
