# Generated by Django 5.0.2 on 2024-12-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_activitydatereport_issuedatereport_reportform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitydatereport',
            old_name='issue_dates',
            new_name='issue_date',
        ),
        migrations.RenameField(
            model_name='issuedatereport',
            old_name='issue_dates',
            new_name='issue_date',
        ),
    ]
