# Generated by Django 5.0.2 on 2024-12-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_rename_issue_dates_activitydatereport_issue_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportform',
            name='activity_dates',
        ),
        migrations.RemoveField(
            model_name='issuedatereport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reportform',
            name='issue_dates',
        ),
        migrations.DeleteModel(
            name='ActivityDateReport',
        ),
        migrations.DeleteModel(
            name='IssueDateReport',
        ),
        migrations.DeleteModel(
            name='ReportForm',
        ),
    ]
