# Generated by Django 5.0.2 on 2024-12-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0008_issuereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='equipment_used',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='materials_used',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='work_completed',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolution_steps',
            field=models.TextField(),
        ),
    ]
